/*






Instead of subclassing Scene, Scene should be an interface that, for example, BattleScene implements (and then extends)

Maybe...

#endScene will always have something to do here...maybe.



 */







var Scene = (function(){


	function Scene(player, sceneManager){

		// TODO instead of passing in player, pass in a scene options object (generated by the SceneManager)
		/*
		{
			player: player,
			sceneName: sceneName,
			nextScene: 'someNextScene',
			previousScene: 'someSceneYouCameFrom',
			etc: andSoOn
		}
		*/
		this.player = player;
	}

	$.extend(Scene.prototype, {
		startScene:function(){
			//TODO sceneManager.createScene(this.name);
		},
		endScene:function(){
			//TODO sceneManager.destroyScene(this);
			alert('You win all the loots!  Restarting demo.');
			viewmodel.player.hp(1000);
			viewmodel.scene(new BattleScene(new Scene(viewmodel.player)) );	//stubbed gunk for prototype
		}
	});

	return Scene;

})();